In [ ]:
#K Nearest Neighbour 

In [1]:
import numpy as np 
import pandas as pd
from sklearn import preprocessing, model_selection, neighbors

In [2]:
#For this algorithm we are taking breast cancer dataset
#The data set is taken from UCI Machine Learning Repository 
#link- 'https://archive.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+(original)'
df=pd.read_csv('breast-cancer-wisconsin.data', header=None)

In [3]:
df.columns=['id','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size' ,'Bare Nuclei','Bland Chromatin ' ,'Normal Nucleoli','Mitoses','Class']

In [4]:
df.head()
#class is gives 2 or 4 
# 2 - bening(Benign refers to a condition, tumor, or growth that is not cancerous)
# 4 - malignant(Malignant refers to cancer cells that can invade and kill nearby tissue and spread to other parts of your body) 

id  Clump Thickness  Uniformity of Cell Size  \
0  1000025                5                        1   
1  1002945                5                        4   
2  1015425                3                        1   
3  1016277                6                        8   
4  1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin   Normal Nucleoli  Mitoses  Class  
0           1                 3                1        1      2  
1          10                 3                2        1      2  
2           2                 3                1        1      2  
3           4                 3                7        1      2  
4           1                 3                1        1      2

In [5]:
#There are 16 instances in Groups 1 to 6 that contain a single missing attribute value denoted by "?"
df.replace('?',-99999, inplace=True) # this will be taken as outlier 

In [6]:
df=df.drop(['id'], axis=1)

In [7]:
x=np.array(df.drop(['Class'],1))
y=np.array(df['Class'])

In [8]:
x_train, x_test, y_train, y_test= model_selection.train_test_split(x,y, test_size=0.2)

In [9]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier()

In [12]:
accuracy=clf.score(x_test,y_test)
print(accuracy)

0.9857142857142858


In [27]:
predict_example=np.array([6,2,1,4,2,2,5,3,1])
predict_example=predict_example.reshape(1,-1)
print(predict_example)

[[6 2 1 4 2 2 5 3 1]]


In [28]:
clf.predict(predict_example)

array([2], dtype=int64)

In [71]:
predict_example=np.array([[6,2,1,4,2,2,5,3,1],[6,5,5,4,5,7,6,3,3]])
predict_example=predict_example.reshape(len(predict_example),-1)
clf.predict(predict_example)

array([2, 4], dtype=int64)